//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Review
    {
        public int Id { get; set; }
        public int Rating { get; set; }
        
        [AllowHtml]
        public string Comment { get; set; }
        public string UserId { get; set; }
        public Nullable<int> AppointmentId { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
